language: python
python:
  - 3.6
install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - nvm install 6
  - nvm use 6
  - npm install --global configurable-http-proxy
script:
  - asv machine --yes --machine=travis
  - asv dev --python=python --machine=travis